language: csharp
solution: "./DotNET/Command Parser.sln"
install:
  - nuget restore "./DotNET/Command Parser.sln"
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release "./DotNET/Command Parser.sln"
  - nunit-console "./DotNET/Tests/bin/Release/Pyratron.Frameworks.Commands.Tests.dll"
